/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/account/': RouteRecordInfo<
      '/account/',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/reset-password': RouteRecordInfo<
      '/auth/reset-password',
      '/auth/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/signout': RouteRecordInfo<
      '/auth/signout',
      '/auth/signout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home': RouteRecordInfo<
      '/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | '/home/'
      | '/home/settings'
      | '/home/settings/'
      | '/home/settings/general/'
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/settings': RouteRecordInfo<
      '/home/settings',
      '/home/settings',
      Record<never, never>,
      Record<never, never>,
      | '/home/settings/'
      | '/home/settings/general/'
    >,
    '/home/settings/': RouteRecordInfo<
      '/home/settings/',
      '/home/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/settings/general/': RouteRecordInfo<
      '/home/settings/general/',
      '/home/settings/general',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invite/[token]': RouteRecordInfo<
      '/invite/[token]',
      '/invite/:token',
      { token: ParamValue<true> },
      { token: ParamValue<false> },
      | never
    >,
    '/w/[workspaceSlug]': RouteRecordInfo<
      '/w/[workspaceSlug]',
      '/w/:workspaceSlug',
      { workspaceSlug: ParamValue<true> },
      { workspaceSlug: ParamValue<false> },
      | '/w/[workspaceSlug]/'
      | '/w/[workspaceSlug]/admin'
      | '/w/[workspaceSlug]/admin/'
      | '/w/[workspaceSlug]/admin/members/'
      | '/w/[workspaceSlug]/admin/workspace/settings'
      | '/w/[workspaceSlug]/admin/workspace/settings/'
    >,
    '/w/[workspaceSlug]/': RouteRecordInfo<
      '/w/[workspaceSlug]/',
      '/w/:workspaceSlug',
      { workspaceSlug: ParamValue<true> },
      { workspaceSlug: ParamValue<false> },
      | never
    >,
    '/w/[workspaceSlug]/admin': RouteRecordInfo<
      '/w/[workspaceSlug]/admin',
      '/w/:workspaceSlug/admin',
      { workspaceSlug: ParamValue<true> },
      { workspaceSlug: ParamValue<false> },
      | '/w/[workspaceSlug]/admin/'
      | '/w/[workspaceSlug]/admin/members/'
      | '/w/[workspaceSlug]/admin/workspace/settings'
      | '/w/[workspaceSlug]/admin/workspace/settings/'
    >,
    '/w/[workspaceSlug]/admin/': RouteRecordInfo<
      '/w/[workspaceSlug]/admin/',
      '/w/:workspaceSlug/admin',
      { workspaceSlug: ParamValue<true> },
      { workspaceSlug: ParamValue<false> },
      | never
    >,
    '/w/[workspaceSlug]/admin/members/': RouteRecordInfo<
      '/w/[workspaceSlug]/admin/members/',
      '/w/:workspaceSlug/admin/members',
      { workspaceSlug: ParamValue<true> },
      { workspaceSlug: ParamValue<false> },
      | never
    >,
    '/w/[workspaceSlug]/admin/workspace/settings': RouteRecordInfo<
      '/w/[workspaceSlug]/admin/workspace/settings',
      '/w/:workspaceSlug/admin/workspace/settings',
      { workspaceSlug: ParamValue<true> },
      { workspaceSlug: ParamValue<false> },
      | '/w/[workspaceSlug]/admin/workspace/settings/'
    >,
    '/w/[workspaceSlug]/admin/workspace/settings/': RouteRecordInfo<
      '/w/[workspaceSlug]/admin/workspace/settings/',
      '/w/:workspaceSlug/admin/workspace/settings',
      { workspaceSlug: ParamValue<true> },
      { workspaceSlug: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/account/index.vue': {
      routes:
        | '/account/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/reset-password.vue': {
      routes:
        | '/auth/reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/signout.vue': {
      routes:
        | '/auth/signout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/home.vue': {
      routes:
        | '/home'
        | '/home/'
        | '/home/settings'
        | '/home/settings/'
        | '/home/settings/general/'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/home/settings.vue': {
      routes:
        | '/home/settings'
        | '/home/settings/'
        | '/home/settings/general/'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/home/settings/index.vue': {
      routes:
        | '/home/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/home/settings/general/index.vue': {
      routes:
        | '/home/settings/general/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/invite/[token].vue': {
      routes:
        | '/invite/[token]'
      views:
        | never
      pathParamNames:
        | 'token'
    }
    'src/pages/w/[workspaceSlug].vue': {
      routes:
        | '/w/[workspaceSlug]'
        | '/w/[workspaceSlug]/'
        | '/w/[workspaceSlug]/admin'
        | '/w/[workspaceSlug]/admin/'
        | '/w/[workspaceSlug]/admin/members/'
        | '/w/[workspaceSlug]/admin/workspace/settings'
        | '/w/[workspaceSlug]/admin/workspace/settings/'
      views:
        | 'default'
      pathParamNames:
        | 'workspaceSlug'
    }
    'src/pages/w/[workspaceSlug]/index.vue': {
      routes:
        | '/w/[workspaceSlug]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/w/[workspaceSlug]/admin.vue': {
      routes:
        | '/w/[workspaceSlug]/admin'
        | '/w/[workspaceSlug]/admin/'
        | '/w/[workspaceSlug]/admin/members/'
        | '/w/[workspaceSlug]/admin/workspace/settings'
        | '/w/[workspaceSlug]/admin/workspace/settings/'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/w/[workspaceSlug]/admin/index.vue': {
      routes:
        | '/w/[workspaceSlug]/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/w/[workspaceSlug]/admin/members/index.vue': {
      routes:
        | '/w/[workspaceSlug]/admin/members/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/w/[workspaceSlug]/admin/workspace/settings.vue': {
      routes:
        | '/w/[workspaceSlug]/admin/workspace/settings'
        | '/w/[workspaceSlug]/admin/workspace/settings/'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/w/[workspaceSlug]/admin/workspace/settings/index.vue': {
      routes:
        | '/w/[workspaceSlug]/admin/workspace/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
